/**
 * StudentProfile model — everything about a student that is NOT identity.
 *
 * Relationship design (his section 13 asks for this to be deliberate):
 *
 *   User 1───1 StudentProfile          userId, unique index
 *   StudentProfile.skills[].skillId  ──> Skill        (many refs, shared catalogue)
 *   StudentProfile.targetRoles[].roleId ──> CareerRole (many refs, shared catalogue)
 *
 * WHY A SEPARATE COLLECTION rather than more fields on User. Authentication data
 * (name, email, password, role, isActive) is read on every single request by the
 * auth middleware; profile data is read only on profile screens. Keeping them
 * apart means a login does not drag a bio, skill list and career goals through
 * bcrypt-adjacent code, and the password hash lives nowhere near data we send to
 * other students later. It is also what TRD.md section 7 lays out: `Users` and
 * `StudentProfiles` are distinct collections.
 *
 * WHY EMBED skills and targetRoles rather than give them their own collections.
 * They have no life of their own — a skill entry is meaningless without the
 * student it belongs to, and it is always read and written together with the
 * rest of the profile. TRD.md section 9 embeds them as arrays for exactly this
 * reason, and his section 13 says "do not normalize or abstract the database
 * excessively." The *skill definition* is shared and normalised (the Skill
 * collection); the *student's relationship to that skill* (their level) is
 * embedded. That split is the whole design.
 *
 * The one thing this model must never do is duplicate name/email/role — those
 * belong to User, and copying them here would let the two drift.
 */

import mongoose from 'mongoose';

import {
  ACHIEVEMENT_TYPE_VALUES,
  ALLOWED_DOCUMENT_MIME_VALUES,
  DOCUMENT_TYPE_VALUES,
  EXPERIENCE_TYPE_VALUES,
  PORTFOLIO_COMPLETION_SECTIONS,
  UPLOAD_LIMITS,
  VERIFICATION_STATUSES,
  VERIFICATION_STATUS_VALUES,
} from '../constants/portfolio.js';
import {
  SKILL_LEVEL_MAX,
  SKILL_LEVEL_MIN,
  SKILL_SOURCES,
  SKILL_SOURCE_VALUES,
} from '../constants/skills.js';

/**
 * One skill a student claims, pointing at the shared catalogue entry.
 *
 * `_id: false` — a student never has the same skill twice (the service and a
 * schema validator both enforce that), so `skillId` is already the natural key
 * and a second synthetic id would only be noise in the payload.
 */
const studentSkillSchema = new mongoose.Schema(
  {
    skillId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Skill',
      required: [true, 'A skill entry must reference a skill'],
    },

    /**
     * Proficiency, 0-100 (TRD.md section 21). The frontend renders the band
     * label; the database stores the number so the assessment engine can later
     * overwrite a self-reported figure with a computed one in the same field.
     */
    level: {
      type: Number,
      required: [true, 'A skill entry must have a level'],
      min: [SKILL_LEVEL_MIN, `Level cannot be below ${SKILL_LEVEL_MIN}`],
      max: [SKILL_LEVEL_MAX, `Level cannot exceed ${SKILL_LEVEL_MAX}`],
    },

    /**
     * False until something authoritative confirms the level. Step 3 only writes
     * self-reported skills, so this stays false throughout; the assessment step
     * is what will set it true. Storing it now is what lets the UI say
     * "self-reported" honestly instead of implying verification.
     */
    verified: {
      type: Boolean,
      default: false,
    },

    /** How the level was arrived at (TRD.md section 9). Manual for every Step 3 write. */
    source: {
      type: String,
      enum: { values: SKILL_SOURCE_VALUES, message: '{VALUE} is not a valid skill source' },
      default: SKILL_SOURCES.MANUAL,
    },
  },
  { _id: false },
);

/** A career goal: a pointer into the CareerRole catalogue plus an ordering. */
const targetRoleSchema = new mongoose.Schema(
  {
    roleId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CareerRole',
      required: [true, 'A target role must reference a career role'],
    },

    /**
     * 1 = primary goal. Lower numbers rank higher. Lets a student say "mainly a
     * backend developer, secondarily full-stack" without a separate model, and
     * gives later matching a defined order to weight by.
     */
    priority: {
      type: Number,
      default: 1,
      min: [1, 'Priority starts at 1'],
    },
  },
  { _id: false },
);

/**
 * Metadata for one stored file. THE BYTES ARE NOT HERE.
 *
 * Mongo holds only the description of the file; the file itself sits on disk
 * under `server/uploads/`, which `.gitignore` already excludes. Storing binaries
 * in the document would bloat every profile read — and a profile is read on
 * nearly every student screen — so the split is a performance decision as much
 * as a storage one.
 *
 * `fileName` is generated by the server and is the only name ever touched by the
 * filesystem. `originalName` is what the student's browser claimed, kept purely
 * so the UI can show a name they recognise and the download can suggest it. It
 * is display data, never a path — see `document.service.js`, which is the single
 * place that turns a `fileName` into a real path.
 *
 * `fileUrl` is an API route, not a static asset URL. There is no static file
 * middleware in `app.js` on purpose: serving the uploads directory statically
 * would make every student's documents readable by anyone who guessed a name.
 * Every read goes through an authenticated controller instead.
 */
const documentMetadataSchema = new mongoose.Schema(
  {
    /** Server-generated, collision-proof, safe by construction. */
    fileName: { type: String, required: true, trim: true, maxlength: 200 },

    /** What the browser claimed. Display only — never used to build a path. */
    originalName: { type: String, required: true, trim: true, maxlength: 200 },

    /** Authenticated download route for this file. */
    fileUrl: { type: String, required: true, trim: true, maxlength: 500 },

    mimeType: {
      type: String,
      required: true,
      enum: {
        values: ALLOWED_DOCUMENT_MIME_VALUES,
        message: '{VALUE} is not an accepted file type',
      },
    },

    /** Bytes actually written, measured server-side — not the claimed length. */
    size: {
      type: Number,
      required: true,
      min: [1, 'An empty file cannot be stored'],
      max: [UPLOAD_LIMITS.maxFileBytes, 'File is too large'],
    },

    documentType: {
      type: String,
      required: true,
      enum: {
        values: DOCUMENT_TYPE_VALUES,
        message: '{VALUE} is not a valid document type',
      },
    },

    uploadedAt: { type: Date, default: Date.now },
  },
  { _id: false },
);

/**
 * Verification state, factored out because five different record types need
 * exactly the same field with exactly the same default.
 *
 * `default: PENDING` with no way for a client to override it is what makes
 * "students cannot self-verify" structural. The field is absent from every
 * editable whitelist in `portfolio.validator.js`, so a request carrying
 * `verificationStatus: 'verified'` is rejected before it reaches here.
 */
const verificationStatusField = () => ({
  type: String,
  enum: {
    values: VERIFICATION_STATUS_VALUES,
    message: '{VALUE} is not a valid verification status',
  },
  default: VERIFICATION_STATUSES.PENDING,
});

/**
 * A project entry. Defined in Step 3 (TRD.md section 9) against the day the
 * portfolio step would need it; Step 6 is that day, so the fields below are an
 * extension of the original three rather than a parallel schema.
 *
 * TWO RENAMES happened here in Step 6: `projectUrl` -> `liveUrl` and
 * `repositoryUrl` -> `githubUrl`, matching the naming used across the rest of the
 * portfolio. This was safe rather than reckless: no service, controller,
 * validator, seed or client file read either name (Step 3 shipped no
 * project-editing UI and `applyEditableFields` never accepted `projects`), so no
 * stored document can contain them and no code path breaks.
 *
 * Neither URL is required. Plenty of good coursework has no public repository,
 * and demanding a GitHub link would quietly exclude the students who most need
 * the portfolio.
 */
const projectSchema = new mongoose.Schema(
  {
    title: { type: String, trim: true, maxlength: 150, required: [true, 'A project needs a title'] },

    /** Required, unlike Step 3: a titled project with no description proves nothing. */
    description: {
      type: String,
      trim: true,
      maxlength: 1000,
      required: [true, 'Describe what the project does'],
    },

    technologies: { type: [String], default: [] },

    /** What the student actually did — "Backend developer", "Team lead". */
    role: { type: String, trim: true, maxlength: 120, default: '' },

    githubUrl: { type: String, trim: true, maxlength: 500, default: '' },
    liveUrl: { type: String, trim: true, maxlength: 500, default: '' },

    startDate: { type: Date, default: null },

    /** Null while `isOngoing` is true — the two are kept consistent by a hook below. */
    endDate: { type: Date, default: null },
    isOngoing: { type: Boolean, default: false },

    /** Optional supporting file: a report, a poster, a screenshot. */
    document: { type: documentMetadataSchema, default: null },

    verificationStatus: verificationStatusField(),
  },
  { _id: true, timestamps: true },
);

/** Certification entry — same Step 3 origin, same Step 6 extension. */
const certificationSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      trim: true,
      maxlength: 150,
      required: [true, 'A certification needs a title'],
    },

    /**
     * Renamed from `issuer` in Step 6 so achievements, experience and
     * certifications all name the awarding body the same way. Same safety
     * argument as the project renames: nothing read the old name.
     */
    issuingOrganization: {
      type: String,
      trim: true,
      maxlength: 150,
      required: [true, 'Say who issued it'],
    },

    issueDate: { type: Date, default: null },

    /** Null means "does not expire", which is the common case. */
    expiryDate: { type: Date, default: null },

    credentialId: { type: String, trim: true, maxlength: 120, default: '' },
    credentialUrl: { type: String, trim: true, maxlength: 500, default: '' },

    document: { type: documentMetadataSchema, default: null },

    verificationStatus: verificationStatusField(),
  },
  { _id: true, timestamps: true },
);

/**
 * Something the student won, published or was awarded.
 *
 * Separate from certifications because the two answer different questions: a
 * certification says "I was taught this and passed", an achievement says "I
 * competed or produced something and it was recognised". Collapsing them would
 * make both unsortable.
 */
const achievementSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      trim: true,
      maxlength: 150,
      required: [true, 'An achievement needs a title'],
    },

    description: {
      type: String,
      trim: true,
      maxlength: 1000,
      required: [true, 'Say what the achievement was'],
    },

    achievementType: {
      type: String,
      enum: {
        values: ACHIEVEMENT_TYPE_VALUES,
        message: '{VALUE} is not a valid achievement type',
      },
      required: [true, 'Choose an achievement type'],
    },

    date: { type: Date, required: [true, 'When did this happen?'] },

    issuingOrganization: { type: String, trim: true, maxlength: 150, default: '' },

    document: { type: documentMetadataSchema, default: null },

    verificationStatus: verificationStatusField(),
  },
  { _id: true, timestamps: true },
);

/**
 * Work history: internships, training, freelance, apprenticeships.
 *
 * DELIBERATELY NOT DERIVED FROM APPLICATIONS. An accepted application on this
 * platform means an organisation said yes, not that the student turned up and
 * finished the work. Auto-creating experience records from application status
 * would put claims in a student's portfolio that nobody made — so this is
 * student-entered and, like everything else here, starts unverified.
 */
const experienceSchema = new mongoose.Schema(
  {
    organization: {
      type: String,
      trim: true,
      maxlength: 150,
      required: [true, 'Name the organisation'],
    },

    role: { type: String, trim: true, maxlength: 120, required: [true, 'What was your role?'] },

    experienceType: {
      type: String,
      enum: {
        values: EXPERIENCE_TYPE_VALUES,
        message: '{VALUE} is not a valid experience type',
      },
      required: [true, 'Choose an experience type'],
    },

    startDate: { type: Date, required: [true, 'When did it start?'] },

    /** Null while `isCurrent` is true. */
    endDate: { type: Date, default: null },
    isCurrent: { type: Boolean, default: false },

    description: { type: String, trim: true, maxlength: 1000, default: '' },

    /** Free text, unlike profile skills: "the CI pipeline" is not a catalogue entry. */
    skillsUsed: { type: [String], default: [] },

    document: { type: documentMetadataSchema, default: null },

    verificationStatus: verificationStatusField(),
  },
  { _id: true, timestamps: true },
);

/**
 * Keeps "ongoing" and "has an end date" from contradicting each other, and
 * rejects an end that precedes its start.
 *
 * Applied as a subdocument validator rather than checked in the service, so the
 * invariant holds however the document was built — including from the seed.
 * `ongoingKey` differs between projects (`isOngoing`) and experience
 * (`isCurrent`) because each reads naturally in its own context.
 */
const applyDateOrderValidation = (schema, ongoingKey) => {
  schema.pre('validate', function checkDateOrder(next) {
    if (this[ongoingKey]) {
      // Trusting the flag over the date: the student ticked "still going".
      this.endDate = null;
      return next();
    }

    if (this.startDate && this.endDate && this.endDate < this.startDate) {
      this.invalidate('endDate', 'The end date cannot be before the start date');
    }

    return next();
  });
};

applyDateOrderValidation(projectSchema, 'isOngoing');
applyDateOrderValidation(experienceSchema, 'isCurrent');

certificationSchema.pre('validate', function checkExpiry(next) {
  if (this.issueDate && this.expiryDate && this.expiryDate < this.issueDate) {
    this.invalidate('expiryDate', 'The expiry date cannot be before the issue date');
  }
  return next();
});

const studentProfileSchema = new mongoose.Schema(
  {
    /**
     * The owner. One profile per user — the unique index is the real guarantee,
     * the service's friendly pre-check is just for a better error message. This
     * is also the ownership boundary his section 9 requires: a profile is
     * fetched and mutated by deriving this from req.user, never from the URL, so
     * one student can never address another's profile.
     */
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'A profile must belong to a user'],
      unique: true, // TRD.md section 9: userId -> Unique Index
      index: true,
    },

    /** Optional short professional title, e.g. "Final-year CS student". DESIGN.md section 26. */
    headline: {
      type: String,
      trim: true,
      maxlength: [120, 'Headline cannot exceed 120 characters'],
      default: '',
    },

    bio: {
      type: String,
      trim: true,
      maxlength: [1000, 'Bio cannot exceed 1000 characters'],
      default: '',
    },

    /**
     * Institution as free text — what a student types in the MVP form
     * (PHASES.md PHASE 2, PRD.md section 6.2 both treat it as text).
     *
     * `institutionId` below is the TRD.md section 9 reference to a future
     * Institution collection. That collection does not exist yet (deferred to
     * the analytics step), so the ref stays null for now; keeping the field and
     * its index means linking students to real institutions later is a
     * backfill, not a migration.
     */
    institutionName: {
      type: String,
      trim: true,
      maxlength: [150, 'Institution name cannot exceed 150 characters'],
      default: '',
    },

    institutionId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Institution',
      default: null,
      index: true, // TRD.md section 9: institutionId -> Index
    },

    degree: {
      type: String,
      trim: true,
      maxlength: [100, 'Degree cannot exceed 100 characters'],
      default: '',
    },

    branch: {
      type: String,
      trim: true,
      maxlength: [100, 'Branch cannot exceed 100 characters'],
      default: '',
    },

    /** Expected graduation year. Bounds are sanity limits, not business rules. */
    graduationYear: {
      type: Number,
      min: [1950, 'Graduation year looks too early'],
      max: [2100, 'Graduation year looks too far ahead'],
      default: null,
    },

    /** Current year of study, 1-6. His section 1 allows "current year if appropriate". */
    currentYear: {
      type: Number,
      min: [1, 'Year of study starts at 1'],
      max: [6, 'Year of study cannot exceed 6'],
      default: null,
    },

    /** CGPA on a 10-point scale (PHASES.md PHASE 2 Academic Information). */
    cgpa: {
      type: Number,
      min: [0, 'CGPA cannot be negative'],
      max: [10, 'CGPA cannot exceed 10'],
      default: null,
    },

    location: {
      type: String,
      trim: true,
      maxlength: [120, 'Location cannot exceed 120 characters'],
      default: '',
    },

    /** Free-text areas of interest, e.g. "Web Development", "Machine Learning". TRD.md section 9. */
    interests: {
      type: [String],
      default: [],
    },

    /** Selected career goals — the "Career Goals" half of this step. */
    targetRoles: {
      type: [targetRoleSchema],
      default: [],
    },

    /** The student's skills — the "Skills" half of this step. */
    skills: {
      type: [studentSkillSchema],
      default: [],
    },

    /**
     * Portfolio sections (Step 6). Embedded rather than given their own
     * collections for the same reason skills are: a project entry has no life
     * without the student it belongs to, and every one of these arrays is read
     * together with the profile on the portfolio screen. One document read
     * renders the whole page.
     *
     * The arrays are capped by the validators (PORTFOLIO_LIMITS), which keeps a
     * profile from growing past a sensible document size.
     */
    projects: {
      type: [projectSchema],
      default: [],
    },

    certifications: {
      type: [certificationSchema],
      default: [],
    },

    achievements: {
      type: [achievementSchema],
      default: [],
    },

    experiences: {
      type: [experienceSchema],
      default: [],
    },

    /**
     * The current resume. Singular, and replaced rather than appended: a student
     * has one current resume, and keeping a history would mean the portfolio
     * could show an out-of-date one to an employer. Uploading again deletes the
     * previous file from disk (see `portfolio.service.js`).
     */
    resume: {
      type: documentMetadataSchema,
      default: null,
    },

    /**
     * TRD.md section 9. The career-readiness percentage from the assessment /
     * readiness engine (TRD.md section 24). NOT computed in this step — null
     * means "not assessed yet", which the UI states plainly rather than showing
     * a misleading 0%.
     */
    readinessScore: {
      type: Number,
      min: 0,
      max: 100,
      default: null,
    },

    /**
     * TRD.md section 9. 0-100, how complete the profile is. This one IS computed
     * here (recomputeCompletion() below), because his section 8 and DESIGN.md
     * section 15.2 both want a completion indicator and it needs no later
     * engine — just the fields already on this document.
     */
    profileCompletion: {
      type: Number,
      min: 0,
      max: 100,
      default: 0,
    },
  },
  {
    timestamps: true,
    toJSON: {
      transform: (_doc, ret) => {
        delete ret.__v;
        return ret;
      },
    },
  },
);

// TRD.md section 9 index. Also the query path for "all students targeting role X".
studentProfileSchema.index({ 'targetRoles.roleId': 1 });

/**
 * Guards against the same skill or role appearing twice in one profile.
 *
 * The service already prevents it on the write path, but a validator here means
 * the invariant holds no matter how a document is constructed — belt and braces
 * for the "no duplicate skill entries" rule in his section 6.
 */
studentProfileSchema.pre('validate', function noDuplicateRefs(next) {
  const skillIds = this.skills.map((entry) => String(entry.skillId));
  if (new Set(skillIds).size !== skillIds.length) {
    return next(new Error('A profile cannot list the same skill twice.'));
  }

  const roleIds = this.targetRoles.map((entry) => String(entry.roleId));
  if (new Set(roleIds).size !== roleIds.length) {
    return next(new Error('A profile cannot list the same career goal twice.'));
  }

  return next();
});

/**
 * Deterministically scores profile completeness out of 100.
 *
 * Weights are declared here, in one place, so the number the dashboard shows and
 * the number stored in the document can never disagree. The set is deliberately
 * the fields a student can fill in Step 3 — nothing depends on a later engine.
 * Called by the service after every write.
 */
const COMPLETION_WEIGHTS = Object.freeze([
  { key: 'bio', weight: 15, filled: (p) => p.bio && p.bio.trim().length > 0 },
  { key: 'institutionName', weight: 15, filled: (p) => p.institutionName && p.institutionName.trim().length > 0 },
  { key: 'branch', weight: 10, filled: (p) => p.branch && p.branch.trim().length > 0 },
  { key: 'graduationYear', weight: 10, filled: (p) => Boolean(p.graduationYear) },
  { key: 'location', weight: 10, filled: (p) => p.location && p.location.trim().length > 0 },
  { key: 'interests', weight: 15, filled: (p) => p.interests.length > 0 },
  { key: 'targetRoles', weight: 10, filled: (p) => p.targetRoles.length > 0 },
  { key: 'skills', weight: 15, filled: (p) => p.skills.length > 0 },
]);

studentProfileSchema.methods.recomputeCompletion = function recomputeCompletion() {
  const earned = COMPLETION_WEIGHTS.reduce(
    (total, field) => total + (field.filled(this) ? field.weight : 0),
    0,
  );
  // The weights sum to 100 (asserted in tests), so clamping is defensive only.
  this.profileCompletion = Math.min(100, Math.max(0, earned));
  return this.profileCompletion;
};

/**
 * Deterministically scores portfolio completeness out of 100.
 *
 * NOT STORED, and that is the point. `profileCompletion` above is a stored field
 * that the service has to remember to recompute; this one is derived on every
 * read from the document in front of it, so it cannot go stale and there is no
 * second number to disagree with the first. Same choice as `readinessScore`'s
 * on-request derivation in the readiness service.
 *
 * No AI is involved anywhere in this function — the weights are a frozen table in
 * `constants/portfolio.js` and the arithmetic is a sum. The same profile always
 * produces the same number.
 *
 * @returns {{completionPercentage: number, completedSections: string[],
 *            missingSections: Array<{key: string, label: string, weight: number, action: string}>}}
 */
studentProfileSchema.methods.computePortfolioCompletion =
  function computePortfolioCompletion() {
    const completedSections = [];
    const missingSections = [];
    let earned = 0;

    for (const section of PORTFOLIO_COMPLETION_SECTIONS) {
      if (section.filled(this)) {
        earned += section.weight;
        completedSections.push(section.key);
      } else {
        missingSections.push({
          key: section.key,
          label: section.label,
          weight: section.weight,
          action: section.action,
        });
      }
    }

    return {
      // The weights sum to 100 (asserted by the Step 6 verification script), so
      // the clamp is defence against a future bad edit, not a live concern.
      completionPercentage: Math.min(100, Math.max(0, earned)),
      completedSections,
      missingSections,
    };
  };

/**
 * The API shape for a profile.
 *
 * Expects skills.skillId and targetRoles.roleId to have been populated by the
 * service; falls back gracefully to bare ids if not, so the method is safe to
 * call in either case. Never includes anything from User beyond the id — the
 * controller merges the safe user object in separately, keeping identity and
 * profile as the two clearly separate things they are.
 */
studentProfileSchema.methods.toProfileObject = function toProfileObject() {
  const mapSkill = (entry) => {
    const populated =
      entry.skillId && typeof entry.skillId === 'object' && entry.skillId.name ? entry.skillId : null;
    return {
      skillId: populated ? populated._id.toString() : entry.skillId.toString(),
      name: populated ? populated.name : undefined,
      slug: populated ? populated.slug : undefined,
      category: populated ? populated.category : undefined,
      tags: populated ? [...(populated.tags ?? [])] : undefined,
      level: entry.level,
      verified: entry.verified,
      source: entry.source,
    };
  };

  const mapRole = (entry) => {
    const populated =
      entry.roleId && typeof entry.roleId === 'object' && entry.roleId.title ? entry.roleId : null;
    return {
      roleId: populated ? populated._id.toString() : entry.roleId.toString(),
      title: populated ? populated.title : undefined,
      category: populated ? populated.category : undefined,
      priority: entry.priority,
    };
  };

  /**
   * File metadata as the client should see it. Returns null rather than an empty
   * object when there is no file, so `profile.resume ? ... : ...` reads honestly
   * in the UI. Nothing here reveals a filesystem path — `fileUrl` is an API
   * route, and the storage layout stays a server detail.
   */
  const mapDocument = (document) =>
    document
      ? {
          fileName: document.fileName,
          originalName: document.originalName,
          fileUrl: document.fileUrl,
          mimeType: document.mimeType,
          size: document.size,
          documentType: document.documentType,
          uploadedAt: document.uploadedAt,
        }
      : null;

  return {
    id: this._id.toString(),
    userId: this.userId.toString(),
    headline: this.headline,
    bio: this.bio,
    institutionName: this.institutionName,
    institutionId: this.institutionId ? this.institutionId.toString() : null,
    degree: this.degree,
    branch: this.branch,
    graduationYear: this.graduationYear,
    currentYear: this.currentYear,
    cgpa: this.cgpa,
    location: this.location,
    interests: [...this.interests],
    targetRoles: this.targetRoles.map(mapRole),
    skills: this.skills.map(mapSkill),
    resume: mapDocument(this.resume),
    projects: this.projects.map((project) => ({
      id: project._id.toString(),
      title: project.title,
      description: project.description,
      technologies: [...project.technologies],
      role: project.role,
      githubUrl: project.githubUrl,
      liveUrl: project.liveUrl,
      startDate: project.startDate,
      endDate: project.endDate,
      isOngoing: project.isOngoing,
      document: mapDocument(project.document),
      verificationStatus: project.verificationStatus,
      createdAt: project.createdAt,
      updatedAt: project.updatedAt,
    })),
    certifications: this.certifications.map((cert) => ({
      id: cert._id.toString(),
      title: cert.title,
      issuingOrganization: cert.issuingOrganization,
      issueDate: cert.issueDate,
      expiryDate: cert.expiryDate,
      credentialId: cert.credentialId,
      credentialUrl: cert.credentialUrl,
      document: mapDocument(cert.document),
      verificationStatus: cert.verificationStatus,
      createdAt: cert.createdAt,
      updatedAt: cert.updatedAt,
    })),
    achievements: this.achievements.map((achievement) => ({
      id: achievement._id.toString(),
      title: achievement.title,
      description: achievement.description,
      achievementType: achievement.achievementType,
      date: achievement.date,
      issuingOrganization: achievement.issuingOrganization,
      document: mapDocument(achievement.document),
      verificationStatus: achievement.verificationStatus,
      createdAt: achievement.createdAt,
      updatedAt: achievement.updatedAt,
    })),
    experiences: this.experiences.map((experience) => ({
      id: experience._id.toString(),
      organization: experience.organization,
      role: experience.role,
      experienceType: experience.experienceType,
      startDate: experience.startDate,
      endDate: experience.endDate,
      isCurrent: experience.isCurrent,
      description: experience.description,
      skillsUsed: [...experience.skillsUsed],
      document: mapDocument(experience.document),
      verificationStatus: experience.verificationStatus,
      createdAt: experience.createdAt,
      updatedAt: experience.updatedAt,
    })),
    readinessScore: this.readinessScore,
    profileCompletion: this.profileCompletion,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt,
  };
};

const StudentProfile = mongoose.model('StudentProfile', studentProfileSchema);

export default StudentProfile;
